### PR TITLE
schemas UUID validation removed

### PR DESCRIPTION
**Pull request by Odraxs**
## Description

Solving issue uuid validation with regular expression that in the future my not show possible errors.
Removed regex field and their involved tests as well.  

Fixes # (#63)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by SanGeeky** [comment]
@Odraxs Thank you for opening this PR, please keep up to date with your branch with the target branch, in this case, is the branch `v0.3`.

**Comment by Odraxs** [comment]
> @Odraxs Thank you for opening this PR, please keep up to date with your branch with the target branch, in this case, is the branch `v0.3`.
Hi, i already update to branch v0.3 and commit the changes into the branch of the pull request, is there anything else I need to do to update the pull request?

**Comment by SanGeeky** [comment]
@Odraxs Thank you for updating your commits, please ensure to push **only your own commits**, and do not forget to sign all the commits to be possible to accept your PR, review this [documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information about signing commits.

**Review by SanGeeky — APPROVED** [review]
:rocket: Thank you for contributing, please verify your signatures to be possible merge your changes

**Review by SanGeeky — APPROVED** [review]

**Pull request merged**
